[features]
seeds = false
skip-lint = false

[programs.localnet]
tachyon_math_library = "tachANmkv5KXR1hSZKoVJ2s5wKrfdgFgb3638k6CvKQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
